/// Item type definitions for 合合游戏 (HeHe Game).
use rand::Rng;

/// Chain type identifies which production/merge family an item belongs to.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ChainType {
    /// 老母鸡 generator chain (auto-generates eggs)
    Poultry,
    /// 鸡蛋 child chain
    Egg,
    /// 茶壶 generator chain (click to generate tea)
    Teapot,
    /// 凉茶 child chain
    CoolTea,
    /// 酒酝圆子 rare child chain
    RiceBall,
    /// 食篓 generator chain (click to generate dough)
    Basket,
    /// 面团 child chain
    Dough,
    /// 西瓜 rare child chain
    Watermelon,
    /// 手作盒 generator chain (click to generate lanterns)
    CraftBox,
    /// 灯笼 child chain
    Lantern,
    /// 妆奁 generator chain (click to generate jewelry)
    Dresser,
    /// 戒指 child chain
    Ring,
    /// 平安扣 rare child chain
    PeaceLock,
    /// 织布机 generator chain (click to generate fabric)
    Loom,
    /// 布匹 child chain
    Fabric,
    /// 荷包 child chain (generated by high-level fabric)
    Pouch,
    /// 红色漆盒 reward gift box (produces 茶壶/食篓/织布机)
    RedBox,
    /// 绿色漆盒 reward gift box (produces 老母鸡/妆奁/手作盒)
    GreenBox,
}

/// One weighted option in a generator's production table.
#[derive(Debug, Clone)]
pub struct GenerationOption {
    /// Item ID to produce.
    pub item_id: String,
    /// Probability weight for this option (absolute, not level-scaled).
    pub weight: u32,
}

/// Definition of a single item in the game.
#[derive(Debug, Clone)]
pub struct ItemDef {
    pub id: String,
    /// The production/merge family this item belongs to.
    /// Used in merge validation (see [`ItemDatabase::can_merge`]) and for future filtering.
    pub chain: ChainType,
    pub level: u32,
    pub name: String,
    pub emoji: String,
    /// Asset path for the item icon image (e.g. "images/items/item_icon.png")
    pub icon_path: Option<String>,
    /// If true, clicking this item generates a child item (costs 1 stamina)
    pub is_generator: bool,
    /// If true, item generates children automatically over time (no stamina cost)
    pub is_auto_generator: bool,
    /// Weighted list of items this generator can produce (used for random selection).
    pub generates: Vec<GenerationOption>,
    /// Primary generated item ID (used for display and as fallback when `generates` is empty).
    pub generates_id: Option<String>,
    /// Auto-generation interval in seconds (only for auto-generators)
    pub auto_gen_interval_secs: f32,
    /// ID of the item produced when two of this item are merged
    pub merge_result_id: Option<String>,
    /// Background color (r, g, b) for display
    pub bg_color: (f32, f32, f32),
    /// Number of items to generate per activation (default 1).
    pub generates_count: u32,
    /// If true, the generator removes itself from the board after generating.
    pub consumes_on_generate: bool,
    /// If > 0, the generator can only be activated this many times total before being consumed.
    /// 0 means unlimited activations (consumes_on_generate still applies for single-use).
    pub max_generate_count: u32,
}

impl ItemDef {
    /// Pick a generated item ID using weighted random selection.
    ///
    /// Uses `self.generates` options weighted by their `weight` field.
    /// Falls back to `self.generates_id` if the table is empty or all weights are zero.
    pub fn pick_generated_item<R: Rng>(&self, rng: &mut R) -> Option<String> {
        let total: u32 = self.generates.iter().map(|o| o.weight).sum();
        if total == 0 {
            return self.generates_id.clone();
        }
        let pick = rng.gen_range(0..total);
        let mut acc = 0u32;
        for opt in &self.generates {
            acc += opt.weight;
            if pick < acc {
                return Some(opt.item_id.clone());
            }
        }
        self.generates_id.clone()
    }
}
