/// Item type definitions for 合合游戏 (HeHe Game).
use rand::Rng;

/// Chain type identifies which production/merge family an item belongs to.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ChainType {
    /// 老母鸡 generator chain (auto-generates eggs)
    Poultry,
    /// 鸡蛋 child chain
    Egg,
    /// 茶壶 generator chain (click to generate tea)
    Teapot,
    /// 凉茶 child chain
    CoolTea,
    /// 酒酝圆子 rare child chain
    RiceBall,
    /// 食篓 generator chain (click to generate dough)
    Basket,
    /// 面团 child chain
    Dough,
    /// 西瓜 rare child chain
    Watermelon,
    /// 手作盒 generator chain (click to generate lanterns)
    CraftBox,
    /// 灯笼 child chain
    Lantern,
    /// 妆奁 generator chain (click to generate jewelry)
    Dresser,
    /// 戒指 child chain
    Ring,
    /// 平安扣 rare child chain
    PeaceLock,
    /// 织布机 generator chain (click to generate fabric)
    Loom,
    /// 布匹 child chain
    Fabric,
    /// 荷包 child chain (generated by high-level fabric)
    Pouch,
    /// 红色漆盒 reward gift box (produces 茶壶/食篓/织布机)
    RedBox,
    /// 绿色漆盒 reward gift box (produces 老母鸡/妆奁/手作盒)
    GreenBox,
}

/// One weighted option in a generator's production table.
#[derive(Debug, Clone)]
pub struct GenerationOption {
    /// Item ID to produce.
    pub item_id: &'static str,
    /// Base probability weight at any generator level.
    pub base_weight: u32,
    /// Additional weight added per generator level (scales rarity up with level).
    pub level_bonus: u32,
}

impl GenerationOption {
    pub const fn new(item_id: &'static str, base_weight: u32, level_bonus: u32) -> Self {
        Self {
            item_id,
            base_weight,
            level_bonus,
        }
    }

    /// Compute effective weight at a given generator level.
    pub fn effective_weight(&self, level: u32) -> u32 {
        self.base_weight + self.level_bonus * level
    }
}

/// Definition of a single item in the game.
#[derive(Debug, Clone)]
pub struct ItemDef {
    pub id: &'static str,
    /// The production/merge family this item belongs to.
    /// Used in merge validation (see [`ItemDatabase::can_merge`]) and for future filtering.
    pub chain: ChainType,
    pub level: u32,
    pub name: &'static str,
    pub emoji: &'static str,
    /// Asset path for the item icon image (e.g. "images/items/item_icon.png")
    pub icon_path: Option<&'static str>,
    /// If true, clicking this item generates a child item (costs 1 stamina)
    pub is_generator: bool,
    /// If true, item generates children automatically over time (no stamina cost)
    pub is_auto_generator: bool,
    /// Weighted list of items this generator can produce (used for random selection).
    pub generates: &'static [GenerationOption],
    /// Primary generated item ID (used for display and as fallback when `generates` is empty).
    pub generates_id: Option<&'static str>,
    /// Auto-generation interval in seconds (only for auto-generators)
    pub auto_gen_interval_secs: f32,
    /// ID of the item produced when two of this item are merged
    pub merge_result_id: Option<&'static str>,
    /// Background color (r, g, b) for display
    pub bg_color: (f32, f32, f32),
}

impl ItemDef {
    /// Pick a generated item ID using weighted random selection.
    ///
    /// Uses `self.generates` options weighted by `effective_weight(self.level)`.
    /// Falls back to `self.generates_id` if the table is empty or all weights are zero.
    pub fn pick_generated_item<R: Rng>(&self, rng: &mut R) -> Option<&'static str> {
        let total: u32 = self
            .generates
            .iter()
            .map(|o| o.effective_weight(self.level))
            .sum();
        if total == 0 {
            return self.generates_id;
        }
        let pick = rng.gen_range(0..total);
        let mut acc = 0u32;
        for opt in self.generates {
            acc += opt.effective_weight(self.level);
            if pick < acc {
                return Some(opt.item_id);
            }
        }
        self.generates_id
    }

    pub(crate) fn child(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
        icon_path: Option<&'static str>,
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            icon_path,
            is_generator: false,
            is_auto_generator: false,
            generates: &[],
            generates_id: None,
            auto_gen_interval_secs: 0.0,
            merge_result_id,
            bg_color,
        }
    }

    pub(crate) fn generator(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        generates: &'static [GenerationOption],
        generates_id: &'static str,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
        icon_path: Option<&'static str>,
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            icon_path,
            is_generator: true,
            is_auto_generator: false,
            generates,
            generates_id: Some(generates_id),
            auto_gen_interval_secs: 0.0,
            merge_result_id,
            bg_color,
        }
    }

    pub(crate) fn auto_generator(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        generates: &'static [GenerationOption],
        generates_id: &'static str,
        interval_secs: f32,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
        icon_path: Option<&'static str>,
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            icon_path,
            is_generator: false,
            is_auto_generator: true,
            generates,
            generates_id: Some(generates_id),
            auto_gen_interval_secs: interval_secs,
            merge_result_id,
            bg_color,
        }
    }
}
