/// Item data definitions for 合合游戏 (HeHe Game)
/// Defines all item chains with their merge relationships and generator properties.
use bevy::prelude::Resource;
use std::collections::HashMap;

/// Chain type identifies which production/merge family an item belongs to.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ChainType {
    /// 老母鸡 generator chain (auto-generates eggs)
    Poultry,
    /// 鸡蛋 child chain
    Egg,
    /// 茶壶 generator chain (click to generate tea)
    Teapot,
    /// 凉茶 child chain
    CoolTea,
    /// 食篓 generator chain (click to generate dough)
    Basket,
    /// 面团 child chain
    Dough,
    /// 手作盒 generator chain (click to generate lanterns)
    CraftBox,
    /// 灯笼 child chain
    Lantern,
    /// 妆奁 generator chain (click to generate jewelry)
    Dresser,
    /// 戒指 child chain
    Ring,
    /// 织布机 generator chain (click to generate fabric)
    Loom,
    /// 布匹 child chain
    Fabric,
    /// 荷包 child chain (generated by high-level fabric)
    Pouch,
}

/// Definition of a single item in the game.
#[derive(Debug, Clone)]
pub struct ItemDef {
    pub id: &'static str,
    /// The production/merge family this item belongs to.
    /// Used in merge validation (see [`ItemDatabase::can_merge`]) and for future filtering.
    pub chain: ChainType,
    pub level: u32,
    pub name: &'static str,
    pub emoji: &'static str,
    /// If true, clicking this item generates a child item (costs 1 stamina)
    pub is_generator: bool,
    /// If true, item generates children automatically over time (no stamina cost)
    pub is_auto_generator: bool,
    /// ID of the item this generator produces
    pub generates_id: Option<&'static str>,
    /// Auto-generation interval in seconds (only for auto-generators)
    pub auto_gen_interval_secs: f32,
    /// ID of the item produced when two of this item are merged
    pub merge_result_id: Option<&'static str>,
    /// Background color (r, g, b) for display
    pub bg_color: (f32, f32, f32),
}

impl ItemDef {
    fn child(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            is_generator: false,
            is_auto_generator: false,
            generates_id: None,
            auto_gen_interval_secs: 0.0,
            merge_result_id,
            bg_color,
        }
    }

    fn generator(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        generates_id: &'static str,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            is_generator: true,
            is_auto_generator: false,
            generates_id: Some(generates_id),
            auto_gen_interval_secs: 0.0,
            merge_result_id,
            bg_color,
        }
    }

    fn auto_generator(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        generates_id: &'static str,
        interval_secs: f32,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            is_generator: true,
            is_auto_generator: true,
            generates_id: Some(generates_id),
            auto_gen_interval_secs: interval_secs,
            merge_result_id,
            bg_color,
        }
    }
}

/// All item definitions in the game.
pub fn all_items() -> Vec<ItemDef> {
    let mut items = Vec::new();

    // ── 老母鸡 (Poultry) generator chain ──────────────────────────────────────
    // Levels 1-5: merge only; levels 6-10: auto-generate eggs every hour
    let pc = (0.85, 0.65, 0.35); // warm orange/brown
    items.push(ItemDef::child("poultry_1", ChainType::Poultry, 1, "老母鸡", "🐔", Some("poultry_2"), pc));
    items.push(ItemDef::child("poultry_2", ChainType::Poultry, 2, "老母鸡", "🐔", Some("poultry_3"), pc));
    items.push(ItemDef::child("poultry_3", ChainType::Poultry, 3, "老母鸡", "🐔", Some("poultry_4"), pc));
    items.push(ItemDef::child("poultry_4", ChainType::Poultry, 4, "老母鸡", "🐔", Some("poultry_5"), pc));
    items.push(ItemDef::child("poultry_5", ChainType::Poultry, 5, "老母鸡", "🐔", Some("poultry_6"), pc));
    items.push(ItemDef::auto_generator("poultry_6", ChainType::Poultry, 6, "老母鸡", "🐔", "egg_1", 3600.0, Some("poultry_7"), pc));
    items.push(ItemDef::auto_generator("poultry_7", ChainType::Poultry, 7, "老母鸡", "🐔", "egg_1", 3000.0, Some("poultry_8"), pc));
    items.push(ItemDef::auto_generator("poultry_8", ChainType::Poultry, 8, "老母鸡", "🐔", "egg_1", 2400.0, Some("poultry_9"), pc));
    items.push(ItemDef::auto_generator("poultry_9", ChainType::Poultry, 9, "老母鸡", "🐔", "egg_1", 1800.0, Some("poultry_10"), pc));
    items.push(ItemDef::auto_generator("poultry_10", ChainType::Poultry, 10, "老母鸡", "🐔", "egg_1", 1200.0, None, pc));

    // ── 鸡蛋 (Egg) child chain (7 levels) ────────────────────────────────────
    let ec = (0.98, 0.95, 0.75); // light yellow
    items.push(ItemDef::child("egg_1", ChainType::Egg, 1, "鸡蛋", "🥚", Some("egg_2"), ec));
    items.push(ItemDef::child("egg_2", ChainType::Egg, 2, "荷包蛋", "🍳", Some("egg_3"), ec));
    items.push(ItemDef::child("egg_3", ChainType::Egg, 3, "蛋炒饭", "🍚", Some("egg_4"), ec));
    items.push(ItemDef::child("egg_4", ChainType::Egg, 4, "蛋炒盖饭", "🍛", Some("egg_5"), ec));
    items.push(ItemDef::child("egg_5", ChainType::Egg, 5, "鸡腿盖饭", "🍗", Some("egg_6"), ec));
    items.push(ItemDef::child("egg_6", ChainType::Egg, 6, "飘香烤鸡", "🍖", Some("egg_7"), ec));
    items.push(ItemDef::child("egg_7", ChainType::Egg, 7, "荷叶蒸鸡", "🪺", None, ec));

    // ── 茶壶 (Teapot) generator chain (11 levels) ─────────────────────────────
    // Lv1-3: merge only; Lv4-11: produces 凉茶
    let tc = (0.75, 0.55, 0.35); // brown
    items.push(ItemDef::child("teapot_1", ChainType::Teapot, 1, "茶壶", "🫖", Some("teapot_2"), tc));
    items.push(ItemDef::child("teapot_2", ChainType::Teapot, 2, "茶壶", "🫖", Some("teapot_3"), tc));
    items.push(ItemDef::child("teapot_3", ChainType::Teapot, 3, "茶壶", "🫖", Some("teapot_4"), tc));
    items.push(ItemDef::generator("teapot_4", ChainType::Teapot, 4, "茶炉", "🫖", "coolTea_1", Some("teapot_5"), tc));
    items.push(ItemDef::generator("teapot_5", ChainType::Teapot, 5, "茶炉", "🫖", "coolTea_1", Some("teapot_6"), tc));
    items.push(ItemDef::generator("teapot_6", ChainType::Teapot, 6, "茶炉", "🫖", "coolTea_1", Some("teapot_7"), tc));
    items.push(ItemDef::generator("teapot_7", ChainType::Teapot, 7, "高级茶炉", "🫖", "coolTea_1", Some("teapot_8"), tc));
    items.push(ItemDef::generator("teapot_8", ChainType::Teapot, 8, "高级茶炉", "🫖", "coolTea_1", Some("teapot_9"), tc));
    items.push(ItemDef::generator("teapot_9", ChainType::Teapot, 9, "高级茶炉", "🫖", "coolTea_2", Some("teapot_10"), tc));
    items.push(ItemDef::generator("teapot_10", ChainType::Teapot, 10, "顶级茶炉", "🫖", "coolTea_2", Some("teapot_11"), tc));
    items.push(ItemDef::generator("teapot_11", ChainType::Teapot, 11, "顶级茶炉", "🫖", "coolTea_2", None, tc));

    // ── 凉茶 (CoolTea) child chain (14 levels) ────────────────────────────────
    let ct = (0.6, 0.85, 0.75); // teal/green
    items.push(ItemDef::child("coolTea_1", ChainType::CoolTea, 1, "凉茶", "🍵", Some("coolTea_2"), ct));
    items.push(ItemDef::child("coolTea_2", ChainType::CoolTea, 2, "菊花茶", "🌼", Some("coolTea_3"), ct));
    items.push(ItemDef::child("coolTea_3", ChainType::CoolTea, 3, "枸杞茶", "🍒", Some("coolTea_4"), ct));
    items.push(ItemDef::child("coolTea_4", ChainType::CoolTea, 4, "罗汉果茶", "🍐", Some("coolTea_5"), ct));
    items.push(ItemDef::child("coolTea_5", ChainType::CoolTea, 5, "薄荷茶", "🌿", Some("coolTea_6"), ct));
    items.push(ItemDef::child("coolTea_6", ChainType::CoolTea, 6, "茅根竹蔗水", "🎋", Some("coolTea_7"), ct));
    items.push(ItemDef::child("coolTea_7", ChainType::CoolTea, 7, "夏枯草茶", "🌾", Some("coolTea_8"), ct));
    items.push(ItemDef::child("coolTea_8", ChainType::CoolTea, 8, "淡竹叶茶", "🍃", Some("coolTea_9"), ct));
    items.push(ItemDef::child("coolTea_9", ChainType::CoolTea, 9, "祛湿茶", "💧", Some("coolTea_10"), ct));
    items.push(ItemDef::child("coolTea_10", ChainType::CoolTea, 10, "五花茶", "🌺", Some("coolTea_11"), ct));
    items.push(ItemDef::child("coolTea_11", ChainType::CoolTea, 11, "二十四味茶", "🧪", Some("coolTea_12"), ct));
    items.push(ItemDef::child("coolTea_12", ChainType::CoolTea, 12, "固元茶", "🫙", Some("coolTea_13"), ct));
    items.push(ItemDef::child("coolTea_13", ChainType::CoolTea, 13, "玉容茶", "🌸", Some("coolTea_14"), ct));
    items.push(ItemDef::child("coolTea_14", ChainType::CoolTea, 14, "千年古茶", "🧉", None, ct));

    // ── 食篓 (Basket) generator chain (11 levels) ────────────────────────────
    // Lv1-4: merge only; Lv5-11: produces 面团
    let bsc = (0.75, 0.65, 0.45); // beige
    items.push(ItemDef::child("basket_1", ChainType::Basket, 1, "食篓", "🧺", Some("basket_2"), bsc));
    items.push(ItemDef::child("basket_2", ChainType::Basket, 2, "食篓", "🧺", Some("basket_3"), bsc));
    items.push(ItemDef::child("basket_3", ChainType::Basket, 3, "食篓", "🧺", Some("basket_4"), bsc));
    items.push(ItemDef::child("basket_4", ChainType::Basket, 4, "食篓", "🧺", Some("basket_5"), bsc));
    items.push(ItemDef::generator("basket_5", ChainType::Basket, 5, "竹华食篓", "🧺", "dough_1", Some("basket_6"), bsc));
    items.push(ItemDef::generator("basket_6", ChainType::Basket, 6, "竹华食篓", "🧺", "dough_1", Some("basket_7"), bsc));
    items.push(ItemDef::generator("basket_7", ChainType::Basket, 7, "竹华食篓", "🧺", "dough_1", Some("basket_8"), bsc));
    items.push(ItemDef::generator("basket_8", ChainType::Basket, 8, "高级食篓", "🧺", "dough_1", Some("basket_9"), bsc));
    items.push(ItemDef::generator("basket_9", ChainType::Basket, 9, "高级食篓", "🧺", "dough_2", Some("basket_10"), bsc));
    items.push(ItemDef::generator("basket_10", ChainType::Basket, 10, "顶级食篓", "🧺", "dough_2", Some("basket_11"), bsc));
    items.push(ItemDef::generator("basket_11", ChainType::Basket, 11, "顶级食篓", "🧺", "dough_2", None, bsc));

    // ── 面团 (Dough/Pastry) child chain (15 levels) ───────────────────────────
    let dc = (0.95, 0.85, 0.65); // light tan
    items.push(ItemDef::child("dough_1", ChainType::Dough, 1, "柿柿如意盒", "🎑", Some("dough_2"), dc));
    items.push(ItemDef::child("dough_2", ChainType::Dough, 2, "桂花糖糕", "🍡", Some("dough_3"), dc));
    items.push(ItemDef::child("dough_3", ChainType::Dough, 3, "玫瑰鲜花饼", "🌸", Some("dough_4"), dc));
    items.push(ItemDef::child("dough_4", ChainType::Dough, 4, "蛋黄酥", "🥐", Some("dough_5"), dc));
    items.push(ItemDef::child("dough_5", ChainType::Dough, 5, "海棠糕", "🎂", Some("dough_6"), dc));
    items.push(ItemDef::child("dough_6", ChainType::Dough, 6, "宫廷糕点", "🍰", Some("dough_7"), dc));
    items.push(ItemDef::child("dough_7", ChainType::Dough, 7, "宫廷糕点", "🍰", Some("dough_8"), dc));
    items.push(ItemDef::child("dough_8", ChainType::Dough, 8, "宫廷糕点", "🍰", Some("dough_9"), dc));
    items.push(ItemDef::child("dough_9", ChainType::Dough, 9, "宫廷糕点", "🍰", Some("dough_10"), dc));
    items.push(ItemDef::child("dough_10", ChainType::Dough, 10, "宫廷糕点", "🍰", Some("dough_11"), dc));
    items.push(ItemDef::child("dough_11", ChainType::Dough, 11, "宫廷糕点", "🍰", Some("dough_12"), dc));
    items.push(ItemDef::child("dough_12", ChainType::Dough, 12, "宫廷糕点", "🍰", Some("dough_13"), dc));
    items.push(ItemDef::child("dough_13", ChainType::Dough, 13, "宫廷糕点", "🍰", Some("dough_14"), dc));
    items.push(ItemDef::child("dough_14", ChainType::Dough, 14, "宫廷糕点", "🍰", Some("dough_15"), dc));
    items.push(ItemDef::child("dough_15", ChainType::Dough, 15, "玉兔摘柿盒", "🍮", None, dc));

    // ── 手作盒 (CraftBox) generator chain (11 levels) ─────────────────────────
    // Lv1-4: merge only; Lv5-11: produces 灯笼
    let cbc = (0.65, 0.45, 0.25); // dark brown
    items.push(ItemDef::child("craftBox_1", ChainType::CraftBox, 1, "手作盒", "📦", Some("craftBox_2"), cbc));
    items.push(ItemDef::child("craftBox_2", ChainType::CraftBox, 2, "手作盒", "📦", Some("craftBox_3"), cbc));
    items.push(ItemDef::child("craftBox_3", ChainType::CraftBox, 3, "手作盒", "📦", Some("craftBox_4"), cbc));
    items.push(ItemDef::child("craftBox_4", ChainType::CraftBox, 4, "手作盒", "📦", Some("craftBox_5"), cbc));
    items.push(ItemDef::generator("craftBox_5", ChainType::CraftBox, 5, "精制手作盒", "📦", "lantern_1", Some("craftBox_6"), cbc));
    items.push(ItemDef::generator("craftBox_6", ChainType::CraftBox, 6, "精制手作盒", "📦", "lantern_1", Some("craftBox_7"), cbc));
    items.push(ItemDef::generator("craftBox_7", ChainType::CraftBox, 7, "精制手作盒", "📦", "lantern_1", Some("craftBox_8"), cbc));
    items.push(ItemDef::generator("craftBox_8", ChainType::CraftBox, 8, "高级手作盒", "📦", "lantern_1", Some("craftBox_9"), cbc));
    items.push(ItemDef::generator("craftBox_9", ChainType::CraftBox, 9, "高级手作盒", "📦", "lantern_2", Some("craftBox_10"), cbc));
    items.push(ItemDef::generator("craftBox_10", ChainType::CraftBox, 10, "顶级手作盒", "📦", "lantern_2", Some("craftBox_11"), cbc));
    items.push(ItemDef::generator("craftBox_11", ChainType::CraftBox, 11, "顶级手作盒", "📦", "lantern_2", None, cbc));

    // ── 灯笼 (Lantern) child chain (12 levels) ────────────────────────────────
    let lc = (0.95, 0.35, 0.25); // red/orange
    items.push(ItemDef::child("lantern_1", ChainType::Lantern, 1, "纸糊灯笼", "🕯️", Some("lantern_2"), lc));
    items.push(ItemDef::child("lantern_2", ChainType::Lantern, 2, "圆灯笼", "🏮", Some("lantern_3"), lc));
    items.push(ItemDef::child("lantern_3", ChainType::Lantern, 3, "彩灯笼", "🪔", Some("lantern_4"), lc));
    items.push(ItemDef::child("lantern_4", ChainType::Lantern, 4, "宫廷灯", "💡", Some("lantern_5"), lc));
    items.push(ItemDef::child("lantern_5", ChainType::Lantern, 5, "宫廷灯", "💡", Some("lantern_6"), lc));
    items.push(ItemDef::child("lantern_6", ChainType::Lantern, 6, "宫廷灯", "💡", Some("lantern_7"), lc));
    items.push(ItemDef::child("lantern_7", ChainType::Lantern, 7, "宫廷灯", "💡", Some("lantern_8"), lc));
    items.push(ItemDef::child("lantern_8", ChainType::Lantern, 8, "宫廷灯", "💡", Some("lantern_9"), lc));
    items.push(ItemDef::child("lantern_9", ChainType::Lantern, 9, "宫廷灯", "💡", Some("lantern_10"), lc));
    items.push(ItemDef::child("lantern_10", ChainType::Lantern, 10, "宫廷灯", "💡", Some("lantern_11"), lc));
    items.push(ItemDef::child("lantern_11", ChainType::Lantern, 11, "宫廷灯", "💡", Some("lantern_12"), lc));
    items.push(ItemDef::child("lantern_12", ChainType::Lantern, 12, "九龙玉灯", "🔆", None, lc));

    // ── 妆奁 (Dresser) generator chain (11 levels) ────────────────────────────
    let drc = (0.85, 0.55, 0.75); // pink/purple
    items.push(ItemDef::child("dresser_1", ChainType::Dresser, 1, "妆奁", "💄", Some("dresser_2"), drc));
    items.push(ItemDef::child("dresser_2", ChainType::Dresser, 2, "妆奁", "💄", Some("dresser_3"), drc));
    items.push(ItemDef::child("dresser_3", ChainType::Dresser, 3, "妆奁", "💄", Some("dresser_4"), drc));
    items.push(ItemDef::child("dresser_4", ChainType::Dresser, 4, "妆奁", "💄", Some("dresser_5"), drc));
    items.push(ItemDef::generator("dresser_5", ChainType::Dresser, 5, "精制妆奁", "💄", "ring_1", Some("dresser_6"), drc));
    items.push(ItemDef::generator("dresser_6", ChainType::Dresser, 6, "精制妆奁", "💄", "ring_1", Some("dresser_7"), drc));
    items.push(ItemDef::generator("dresser_7", ChainType::Dresser, 7, "精制妆奁", "💄", "ring_1", Some("dresser_8"), drc));
    items.push(ItemDef::generator("dresser_8", ChainType::Dresser, 8, "高级妆奁", "💄", "ring_1", Some("dresser_9"), drc));
    items.push(ItemDef::generator("dresser_9", ChainType::Dresser, 9, "高级妆奁", "💄", "ring_2", Some("dresser_10"), drc));
    items.push(ItemDef::generator("dresser_10", ChainType::Dresser, 10, "顶级妆奁", "💄", "ring_2", Some("dresser_11"), drc));
    items.push(ItemDef::generator("dresser_11", ChainType::Dresser, 11, "顶级妆奁", "💄", "ring_2", None, drc));

    // ── 戒指 (Ring/Jewelry) child chain (11 levels) ───────────────────────────
    let rc = (0.85, 0.75, 0.25); // gold
    items.push(ItemDef::child("ring_1", ChainType::Ring, 1, "金戒指", "💍", Some("ring_2"), rc));
    items.push(ItemDef::child("ring_2", ChainType::Ring, 2, "雕花耳坠", "📿", Some("ring_3"), rc));
    items.push(ItemDef::child("ring_3", ChainType::Ring, 3, "银镯子", "⭕", Some("ring_4"), rc));
    items.push(ItemDef::child("ring_4", ChainType::Ring, 4, "翡翠镯", "💚", Some("ring_5"), rc));
    items.push(ItemDef::child("ring_5", ChainType::Ring, 5, "龙凤佩", "💎", Some("ring_6"), rc));
    items.push(ItemDef::child("ring_6", ChainType::Ring, 6, "玉手镯", "🔮", Some("ring_7"), rc));
    items.push(ItemDef::child("ring_7", ChainType::Ring, 7, "皇室项链", "✨", Some("ring_8"), rc));
    items.push(ItemDef::child("ring_8", ChainType::Ring, 8, "凤钗", "🌟", Some("ring_9"), rc));
    items.push(ItemDef::child("ring_9", ChainType::Ring, 9, "宫廷发冠", "👑", Some("ring_10"), rc));
    items.push(ItemDef::child("ring_10", ChainType::Ring, 10, "龙纹金冠", "🏆", Some("ring_11"), rc));
    items.push(ItemDef::child("ring_11", ChainType::Ring, 11, "御赐凤冠", "🎖️", None, rc));

    // ── 织布机 (Loom) generator chain (11 levels) ─────────────────────────────
    let lmc = (0.55, 0.65, 0.85); // blue
    items.push(ItemDef::child("loom_1", ChainType::Loom, 1, "织布机", "🪡", Some("loom_2"), lmc));
    items.push(ItemDef::child("loom_2", ChainType::Loom, 2, "织布机", "🪡", Some("loom_3"), lmc));
    items.push(ItemDef::child("loom_3", ChainType::Loom, 3, "织布机", "🪡", Some("loom_4"), lmc));
    items.push(ItemDef::child("loom_4", ChainType::Loom, 4, "织布机", "🪡", Some("loom_5"), lmc));
    items.push(ItemDef::generator("loom_5", ChainType::Loom, 5, "精制织布机", "🪡", "fabric_1", Some("loom_6"), lmc));
    items.push(ItemDef::generator("loom_6", ChainType::Loom, 6, "精制织布机", "🪡", "fabric_1", Some("loom_7"), lmc));
    items.push(ItemDef::generator("loom_7", ChainType::Loom, 7, "精制织布机", "🪡", "fabric_1", Some("loom_8"), lmc));
    items.push(ItemDef::generator("loom_8", ChainType::Loom, 8, "高级织布机", "🪡", "fabric_1", Some("loom_9"), lmc));
    items.push(ItemDef::generator("loom_9", ChainType::Loom, 9, "高级织布机", "🪡", "fabric_2", Some("loom_10"), lmc));
    items.push(ItemDef::generator("loom_10", ChainType::Loom, 10, "顶级织布机", "🪡", "fabric_2", Some("loom_11"), lmc));
    items.push(ItemDef::generator("loom_11", ChainType::Loom, 11, "顶级织布机", "🪡", "fabric_2", None, lmc));

    // ── 布匹 (Fabric) child chain (5 levels) ──────────────────────────────────
    let fc = (0.75, 0.85, 0.95); // light blue
    items.push(ItemDef::child("fabric_1", ChainType::Fabric, 1, "白色布匹", "🧵", Some("fabric_2"), fc));
    items.push(ItemDef::child("fabric_2", ChainType::Fabric, 2, "描金绣花手袋", "👜", Some("fabric_3"), fc));
    items.push(ItemDef::child("fabric_3", ChainType::Fabric, 3, "香囊", "🎒", Some("fabric_4"), fc));
    items.push(ItemDef::child("fabric_4", ChainType::Fabric, 4, "货郎包", "💼", Some("fabric_5"), fc));
    // fabric_5 can also produce pouch_1 when merged, represented via merge_result_id only
    items.push(ItemDef::child("fabric_5", ChainType::Fabric, 5, "绸缎", "🎀", Some("pouch_1"), fc));

    // ── 荷包 (Pouch) child chain (10 levels) ──────────────────────────────────
    // pouch_1 is produced when two fabric_5 are merged (high-end result)
    let poc = (0.65, 0.75, 0.95); // periwinkle
    items.push(ItemDef::child("pouch_1", ChainType::Pouch, 1, "荷包", "👛", Some("pouch_2"), poc));
    items.push(ItemDef::child("pouch_2", ChainType::Pouch, 2, "绣花荷包", "🪷", Some("pouch_3"), poc));
    items.push(ItemDef::child("pouch_3", ChainType::Pouch, 3, "龙纹荷包", "🐉", Some("pouch_4"), poc));
    items.push(ItemDef::child("pouch_4", ChainType::Pouch, 4, "锦绣荷包", "🌈", Some("pouch_5"), poc));
    items.push(ItemDef::child("pouch_5", ChainType::Pouch, 5, "宫廷香囊", "🏅", Some("pouch_6"), poc));
    items.push(ItemDef::child("pouch_6", ChainType::Pouch, 6, "彩绣荷包", "🎨", Some("pouch_7"), poc));
    items.push(ItemDef::child("pouch_7", ChainType::Pouch, 7, "金丝荷包", "💰", Some("pouch_8"), poc));
    items.push(ItemDef::child("pouch_8", ChainType::Pouch, 8, "御用香囊", "🎗️", Some("pouch_9"), poc));
    items.push(ItemDef::child("pouch_9", ChainType::Pouch, 9, "传世荷包", "🎁", Some("pouch_10"), poc));
    items.push(ItemDef::child("pouch_10", ChainType::Pouch, 10, "凤凰荷包", "🦚", None, poc));

    items
}

/// Lookup table for items by ID.
#[derive(Debug, Resource)]
pub struct ItemDatabase {
    pub items: HashMap<String, ItemDef>,
}

impl ItemDatabase {
    pub fn new() -> Self {
        let mut items = HashMap::new();
        for item in all_items() {
            items.insert(item.id.to_string(), item);
        }
        Self { items }
    }

    pub fn get(&self, id: &str) -> Option<&ItemDef> {
        self.items.get(id)
    }

    /// Check whether two items can be merged.
    ///
    /// Merge is possible when both items:
    /// - exist in the database
    /// - have the same item ID (which implies same chain and same level)
    /// - have a `merge_result_id` (i.e. are not at the maximum level)
    ///
    /// The `chain` field on each `ItemDef` uniquely identifies which production
    /// family the item belongs to; because we require `id_a == id_b`, the chains
    /// are guaranteed to match without a redundant comparison.
    pub fn can_merge(&self, id_a: &str, id_b: &str) -> bool {
        if id_a != id_b {
            return false;
        }
        if let Some(item) = self.get(id_a) {
            // Sanity-check: same id implies same chain and same level
            debug_assert!(
                matches!(self.get(id_b), Some(b) if std::mem::discriminant(&b.chain)
                    == std::mem::discriminant(&item.chain) && b.level == item.level),
                "Two items with the same id must belong to the same chain and level"
            );
            item.merge_result_id.is_some()
        } else {
            false
        }
    }
}

impl Default for ItemDatabase {
    fn default() -> Self {
        Self::new()
    }
}
