/// Item data definitions for 合合游戏 (HeHe Game)
/// Defines all item chains with their merge relationships and generator properties.
use bevy::prelude::Resource;
use rand::Rng;
use std::collections::HashMap;

/// Chain type identifies which production/merge family an item belongs to.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ChainType {
    /// 老母鸡 generator chain (auto-generates eggs)
    Poultry,
    /// 鸡蛋 child chain
    Egg,
    /// 茶壶 generator chain (click to generate tea)
    Teapot,
    /// 凉茶 child chain
    CoolTea,
    /// 酒酝圆子 rare child chain
    RiceBall,
    /// 食篓 generator chain (click to generate dough)
    Basket,
    /// 面团 child chain
    Dough,
    /// 西瓜 rare child chain
    Watermelon,
    /// 手作盒 generator chain (click to generate lanterns)
    CraftBox,
    /// 灯笼 child chain
    Lantern,
    /// 妆奁 generator chain (click to generate jewelry)
    Dresser,
    /// 戒指 child chain
    Ring,
    /// 平安扣 rare child chain
    PeaceLock,
    /// 织布机 generator chain (click to generate fabric)
    Loom,
    /// 布匹 child chain
    Fabric,
    /// 荷包 child chain (generated by high-level fabric)
    Pouch,
    /// 红色漆盒 reward gift box (produces 茶壶/食篓/织布机)
    RedBox,
    /// 绿色漆盒 reward gift box (produces 老母鸡/妆奁/手作盒)
    GreenBox,
}

/// One weighted option in a generator's production table.
#[derive(Debug, Clone)]
pub struct GenerationOption {
    /// Item ID to produce.
    pub item_id: &'static str,
    /// Base probability weight at any generator level.
    pub base_weight: u32,
    /// Additional weight added per generator level (scales rarity up with level).
    pub level_bonus: u32,
}

impl GenerationOption {
    pub const fn new(item_id: &'static str, base_weight: u32, level_bonus: u32) -> Self {
        Self { item_id, base_weight, level_bonus }
    }

    /// Compute effective weight at a given generator level.
    pub fn effective_weight(&self, level: u32) -> u32 {
        self.base_weight + self.level_bonus * level
    }
}

/// Definition of a single item in the game.
#[derive(Debug, Clone)]
pub struct ItemDef {
    pub id: &'static str,
    /// The production/merge family this item belongs to.
    /// Used in merge validation (see [`ItemDatabase::can_merge`]) and for future filtering.
    pub chain: ChainType,
    pub level: u32,
    pub name: &'static str,
    pub emoji: &'static str,
    /// Asset path for the item icon image (e.g. "item_icon_10601.png")
    pub icon_path: Option<&'static str>,
    /// If true, clicking this item generates a child item (costs 1 stamina)
    pub is_generator: bool,
    /// If true, item generates children automatically over time (no stamina cost)
    pub is_auto_generator: bool,
    /// Weighted list of items this generator can produce (used for random selection).
    pub generates: &'static [GenerationOption],
    /// Primary generated item ID (used for display and as fallback when `generates` is empty).
    pub generates_id: Option<&'static str>,
    /// Auto-generation interval in seconds (only for auto-generators)
    pub auto_gen_interval_secs: f32,
    /// ID of the item produced when two of this item are merged
    pub merge_result_id: Option<&'static str>,
    /// Background color (r, g, b) for display
    pub bg_color: (f32, f32, f32),
}

impl ItemDef {
    /// Pick a generated item ID using weighted random selection.
    ///
    /// Uses `self.generates` options weighted by `effective_weight(self.level)`.
    /// Falls back to `self.generates_id` if the table is empty or all weights are zero.
    pub fn pick_generated_item<R: Rng>(&self, rng: &mut R) -> Option<&'static str> {
        let total: u32 = self.generates.iter().map(|o| o.effective_weight(self.level)).sum();
        if total == 0 {
            return self.generates_id;
        }
        let pick = rng.gen_range(0..total);
        let mut acc = 0u32;
        for opt in self.generates {
            acc += opt.effective_weight(self.level);
            if pick < acc {
                return Some(opt.item_id);
            }
        }
        self.generates_id
    }

    fn child(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
        icon_path: Option<&'static str>,
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            icon_path,
            is_generator: false,
            is_auto_generator: false,
            generates: &[],
            generates_id: None,
            auto_gen_interval_secs: 0.0,
            merge_result_id,
            bg_color,
        }
    }

    fn generator(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        generates: &'static [GenerationOption],
        generates_id: &'static str,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
        icon_path: Option<&'static str>,
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            icon_path,
            is_generator: true,
            is_auto_generator: false,
            generates,
            generates_id: Some(generates_id),
            auto_gen_interval_secs: 0.0,
            merge_result_id,
            bg_color,
        }
    }

    fn auto_generator(
        id: &'static str,
        chain: ChainType,
        level: u32,
        name: &'static str,
        emoji: &'static str,
        generates: &'static [GenerationOption],
        generates_id: &'static str,
        interval_secs: f32,
        merge_result_id: Option<&'static str>,
        bg_color: (f32, f32, f32),
        icon_path: Option<&'static str>,
    ) -> Self {
        Self {
            id,
            chain,
            level,
            name,
            emoji,
            icon_path,
            is_generator: true,
            is_auto_generator: true,
            generates,
            generates_id: Some(generates_id),
            auto_gen_interval_secs: interval_secs,
            merge_result_id,
            bg_color,
        }
    }
}

// ── Static generation option tables ──────────────────────────────────────────
// These live as static arrays so they can be referenced by &'static [GenerationOption].

/// 老母鸡 auto-gen: 鸡蛋 only
static POULTRY_GEN: &[GenerationOption] = &[GenerationOption::new("egg_1", 100, 0)];

/// 茶壶 gen: 凉茶 (main) + 菊花茶 (level-scaled) + 酒酝圆子 (rare, scales with level)
static TEA_GEN: &[GenerationOption] = &[
    GenerationOption::new("coolTea_1", 85, 0),
    GenerationOption::new("coolTea_2", 0, 2),   // Lv4→8, Lv11→22
    GenerationOption::new("riceBall_1", 5, 1),  // Lv4→9, Lv11→16
];

/// 食篓 gen: 面团 (main) + 汤圆 (level-scaled) + 西瓜 (rare, scales with level)
static BASKET_GEN: &[GenerationOption] = &[
    GenerationOption::new("dough_1", 85, 0),
    GenerationOption::new("dough_2", 0, 2),
    GenerationOption::new("watermelon_1", 5, 1),
];

/// 手作盒 gen: 纸糊灯笼 (main) + 圆灯笼 (level-scaled)
static CRAFTBOX_GEN: &[GenerationOption] = &[
    GenerationOption::new("lantern_1", 88, 0),
    GenerationOption::new("lantern_2", 0, 2),
];

/// 妆奁 gen: 金戒指 (main) + 雕花耳坠 (level-scaled) + 平安扣 (rare, scales with level)
static DRESSER_GEN: &[GenerationOption] = &[
    GenerationOption::new("ring_1", 85, 0),
    GenerationOption::new("ring_2", 0, 2),
    GenerationOption::new("peaceLock_1", 5, 1),
];

/// 织布机 gen: 白色布匹 (main) + 彩色布匹 (level-scaled)
static LOOM_GEN: &[GenerationOption] = &[
    GenerationOption::new("fabric_1", 88, 0),
    GenerationOption::new("fabric_2", 0, 2),
];

/// 绫罗布匹 (fabric_5) gen: 绣花荷包 (main) + 绣花荷包Lv2 (level-scaled)
static FABRIC5_GEN: &[GenerationOption] = &[
    GenerationOption::new("pouch_1", 90, 0),
    GenerationOption::new("pouch_2", 0, 2),
];

/// 红色漆盒 Lv1 gen: 茶壶/食篓/织布机 (equal chance)
static RED_BOX_LV1_GEN: &[GenerationOption] = &[
    GenerationOption::new("teapot_1", 1, 0),
    GenerationOption::new("basket_1", 1, 0),
    GenerationOption::new("loom_1", 1, 0),
];
/// 红色漆盒 Lv2 gen: 茶壶Lv2/食篓Lv2/织布机Lv2 (equal chance)
static RED_BOX_LV2_GEN: &[GenerationOption] = &[
    GenerationOption::new("teapot_2", 1, 0),
    GenerationOption::new("basket_2", 1, 0),
    GenerationOption::new("loom_2", 1, 0),
];

/// 绿色漆盒 Lv1 gen: 老母鸡/妆奁/手作盒 (equal chance)
static GREEN_BOX_LV1_GEN: &[GenerationOption] = &[
    GenerationOption::new("poultry_1", 1, 0),
    GenerationOption::new("dresser_1", 1, 0),
    GenerationOption::new("craftBox_1", 1, 0),
];
/// 绿色漆盒 Lv2 gen: 老母鸡Lv2/妆奁Lv2/手作盒Lv2 (equal chance)
static GREEN_BOX_LV2_GEN: &[GenerationOption] = &[
    GenerationOption::new("poultry_2", 1, 0),
    GenerationOption::new("dresser_2", 1, 0),
    GenerationOption::new("craftBox_2", 1, 0),
];

/// All item definitions in the game.
pub fn all_items() -> Vec<ItemDef> {
    let mut items = Vec::new();

    // ── 老母鸡 (Poultry) auto-generator chain (10 levels) ────────────────────
    // Lv1-5: merge only; Lv6-10: auto-generate 鸡蛋 every hour (storage capacity 6)
    let pc = (0.85, 0.65, 0.35); // warm orange/brown
    items.push(ItemDef::child("poultry_1", ChainType::Poultry, 1, "老母鸡", "🐔", Some("poultry_2"), pc, Some("item_icon_10601.png")));
    items.push(ItemDef::child("poultry_2", ChainType::Poultry, 2, "老母鸡", "🐔", Some("poultry_3"), pc, Some("item_icon_10602.png")));
    items.push(ItemDef::child("poultry_3", ChainType::Poultry, 3, "老母鸡", "🐔", Some("poultry_4"), pc, Some("item_icon_10603.png")));
    items.push(ItemDef::child("poultry_4", ChainType::Poultry, 4, "老母鸡", "🐔", Some("poultry_5"), pc, Some("item_icon_10604.png")));
    items.push(ItemDef::child("poultry_5", ChainType::Poultry, 5, "老母鸡", "🐔", Some("poultry_6"), pc, Some("item_icon_10605.png")));
    items.push(ItemDef::auto_generator("poultry_6",  ChainType::Poultry, 6,  "老母鸡", "🐔", POULTRY_GEN, "egg_1", 3600.0, Some("poultry_7"),  pc, Some("item_icon_10606.png")));
    items.push(ItemDef::auto_generator("poultry_7",  ChainType::Poultry, 7,  "老母鸡", "🐔", POULTRY_GEN, "egg_1", 3600.0, Some("poultry_8"),  pc, Some("item_icon_10607.png")));
    items.push(ItemDef::auto_generator("poultry_8",  ChainType::Poultry, 8,  "老母鸡", "🐔", POULTRY_GEN, "egg_1", 3600.0, Some("poultry_9"),  pc, Some("item_icon_10608.png")));
    items.push(ItemDef::auto_generator("poultry_9",  ChainType::Poultry, 9,  "老母鸡", "🐔", POULTRY_GEN, "egg_1", 3600.0, Some("poultry_10"), pc, Some("item_icon_10609.png")));
    items.push(ItemDef::auto_generator("poultry_10", ChainType::Poultry, 10, "老母鸡", "🐔", POULTRY_GEN, "egg_1", 3600.0, None,             pc, Some("item_icon_10610.png")));

    // ── 鸡蛋 (Egg) child chain (7 levels) ────────────────────────────────────
    let ec = (0.98, 0.95, 0.75); // light yellow
    items.push(ItemDef::child("egg_1", ChainType::Egg, 1, "鸡蛋",   "🥚", Some("egg_2"), ec, Some("item_icon_20801.png")));
    items.push(ItemDef::child("egg_2", ChainType::Egg, 2, "荷包蛋", "🍳", Some("egg_3"), ec, Some("item_icon_20802.png")));
    items.push(ItemDef::child("egg_3", ChainType::Egg, 3, "蛋炒饭", "🍚", Some("egg_4"), ec, Some("item_icon_20803.png")));
    items.push(ItemDef::child("egg_4", ChainType::Egg, 4, "蛋炒盖饭", "🍛", Some("egg_5"), ec, Some("item_icon_20804.png")));
    items.push(ItemDef::child("egg_5", ChainType::Egg, 5, "鸡腿盖饭", "🍗", Some("egg_6"), ec, Some("item_icon_20805.png")));
    items.push(ItemDef::child("egg_6", ChainType::Egg, 6, "飘香烤鸡", "🍖", Some("egg_7"), ec, Some("item_icon_20806.png")));
    items.push(ItemDef::child("egg_7", ChainType::Egg, 7, "荷叶蒸鸡", "🪺", None,        ec, Some("item_icon_20807.png")));

    // ── 茶壶 (Teapot) generator chain (11 levels) ─────────────────────────────
    // Lv1-3: merge only; Lv4-11: weighted-generates 凉茶 + rare 酒酝圆子
    let tc = (0.75, 0.55, 0.35); // brown
    items.push(ItemDef::child("teapot_1", ChainType::Teapot, 1, "茶壶", "🫖", Some("teapot_2"), tc, Some("item_icon_10201.png")));
    items.push(ItemDef::child("teapot_2", ChainType::Teapot, 2, "茶壶", "🫖", Some("teapot_3"), tc, Some("item_icon_10202.png")));
    items.push(ItemDef::child("teapot_3", ChainType::Teapot, 3, "茶壶", "🫖", Some("teapot_4"), tc, Some("item_icon_10203.png")));
    items.push(ItemDef::generator("teapot_4",  ChainType::Teapot, 4,  "茶炉",   "🫖", TEA_GEN, "coolTea_1", Some("teapot_5"),  tc, Some("item_icon_10204.png")));
    items.push(ItemDef::generator("teapot_5",  ChainType::Teapot, 5,  "茶炉",   "🫖", TEA_GEN, "coolTea_1", Some("teapot_6"),  tc, Some("item_icon_10205.png")));
    items.push(ItemDef::generator("teapot_6",  ChainType::Teapot, 6,  "茶炉",   "🫖", TEA_GEN, "coolTea_1", Some("teapot_7"),  tc, Some("item_icon_10206.png")));
    items.push(ItemDef::generator("teapot_7",  ChainType::Teapot, 7,  "高级茶炉", "🫖", TEA_GEN, "coolTea_1", Some("teapot_8"),  tc, Some("item_icon_10207.png")));
    items.push(ItemDef::generator("teapot_8",  ChainType::Teapot, 8,  "高级茶炉", "🫖", TEA_GEN, "coolTea_1", Some("teapot_9"),  tc, Some("item_icon_10208.png")));
    items.push(ItemDef::generator("teapot_9",  ChainType::Teapot, 9,  "高级茶炉", "🫖", TEA_GEN, "coolTea_1", Some("teapot_10"), tc, Some("item_icon_10209.png")));
    items.push(ItemDef::generator("teapot_10", ChainType::Teapot, 10, "顶级茶炉", "🫖", TEA_GEN, "coolTea_1", Some("teapot_11"), tc, Some("item_icon_10210.png")));
    items.push(ItemDef::generator("teapot_11", ChainType::Teapot, 11, "顶级茶炉", "🫖", TEA_GEN, "coolTea_1", None,             tc, Some("item_icon_10211.png")));

    // ── 凉茶 (CoolTea) child chain (14 levels) ────────────────────────────────
    let ct = (0.6, 0.85, 0.75); // teal/green
    items.push(ItemDef::child("coolTea_1",  ChainType::CoolTea, 1,  "凉茶",       "🍵", Some("coolTea_2"),  ct, Some("item_icon_20301.png")));
    items.push(ItemDef::child("coolTea_2",  ChainType::CoolTea, 2,  "菊花茶",     "🌼", Some("coolTea_3"),  ct, Some("item_icon_20302.png")));
    items.push(ItemDef::child("coolTea_3",  ChainType::CoolTea, 3,  "枸杞茶",     "🍒", Some("coolTea_4"),  ct, Some("item_icon_20303.png")));
    items.push(ItemDef::child("coolTea_4",  ChainType::CoolTea, 4,  "罗汉果茶",   "🍐", Some("coolTea_5"),  ct, Some("item_icon_20304.png")));
    items.push(ItemDef::child("coolTea_5",  ChainType::CoolTea, 5,  "薄荷茶",     "🌿", Some("coolTea_6"),  ct, Some("item_icon_20305.png")));
    items.push(ItemDef::child("coolTea_6",  ChainType::CoolTea, 6,  "茅根竹蔗水", "🎋", Some("coolTea_7"),  ct, Some("item_icon_20306.png")));
    items.push(ItemDef::child("coolTea_7",  ChainType::CoolTea, 7,  "夏枯草茶",   "🌾", Some("coolTea_8"),  ct, Some("item_icon_20307.png")));
    items.push(ItemDef::child("coolTea_8",  ChainType::CoolTea, 8,  "淡竹叶茶",   "🍃", Some("coolTea_9"),  ct, Some("item_icon_20308.png")));
    items.push(ItemDef::child("coolTea_9",  ChainType::CoolTea, 9,  "祛湿茶",     "💧", Some("coolTea_10"), ct, Some("item_icon_20309.png")));
    items.push(ItemDef::child("coolTea_10", ChainType::CoolTea, 10, "五花茶",     "🌺", Some("coolTea_11"), ct, Some("item_icon_20310.png")));
    items.push(ItemDef::child("coolTea_11", ChainType::CoolTea, 11, "二十四味茶", "🧪", Some("coolTea_12"), ct, Some("item_icon_20311.png")));
    items.push(ItemDef::child("coolTea_12", ChainType::CoolTea, 12, "固元茶",     "🫙", Some("coolTea_13"), ct, Some("item_icon_20312.png")));
    items.push(ItemDef::child("coolTea_13", ChainType::CoolTea, 13, "玉容茶",     "🌸", Some("coolTea_14"), ct, Some("item_icon_20313.png")));
    items.push(ItemDef::child("coolTea_14", ChainType::CoolTea, 14, "千年古茶",   "🧉", None,               ct, Some("item_icon_20314.png")));

    // ── 酒酝圆子 (RiceBall) rare child chain (7 levels) ───────────────────────
    let rbc = (0.92, 0.85, 0.70); // warm cream
    items.push(ItemDef::child("riceBall_1", ChainType::RiceBall, 1, "酒酝圆子", "🍡", Some("riceBall_2"), rbc, Some("item_icon_20401.png")));
    items.push(ItemDef::child("riceBall_2", ChainType::RiceBall, 2, "酒酝圆子", "🍡", Some("riceBall_3"), rbc, Some("item_icon_20402.png")));
    items.push(ItemDef::child("riceBall_3", ChainType::RiceBall, 3, "酒酝圆子", "🍡", Some("riceBall_4"), rbc, Some("item_icon_20403.png")));
    items.push(ItemDef::child("riceBall_4", ChainType::RiceBall, 4, "酒酝圆子", "🍡", Some("riceBall_5"), rbc, Some("item_icon_20404.png")));
    items.push(ItemDef::child("riceBall_5", ChainType::RiceBall, 5, "酒酝圆子", "🍡", Some("riceBall_6"), rbc, Some("item_icon_20405.png")));
    items.push(ItemDef::child("riceBall_6", ChainType::RiceBall, 6, "酒酝圆子", "🍡", Some("riceBall_7"), rbc, Some("item_icon_20406.png")));
    items.push(ItemDef::child("riceBall_7", ChainType::RiceBall, 7, "极品酒酝圆子", "🍡", None,          rbc, Some("item_icon_20407.png")));

    // ── 食篓 (Basket) generator chain (11 levels) ────────────────────────────
    // Lv1-4: merge only; Lv5-11: weighted-generates 面团 + rare 西瓜
    let bsc = (0.75, 0.65, 0.45); // beige
    items.push(ItemDef::child("basket_1", ChainType::Basket, 1, "食篓", "🧺", Some("basket_2"), bsc, Some("item_icon_10101.png")));
    items.push(ItemDef::child("basket_2", ChainType::Basket, 2, "食篓", "🧺", Some("basket_3"), bsc, Some("item_icon_10102.png")));
    items.push(ItemDef::child("basket_3", ChainType::Basket, 3, "食篓", "🧺", Some("basket_4"), bsc, Some("item_icon_10103.png")));
    items.push(ItemDef::child("basket_4", ChainType::Basket, 4, "食篓", "🧺", Some("basket_5"), bsc, Some("item_icon_10104.png")));
    items.push(ItemDef::generator("basket_5",  ChainType::Basket, 5,  "竹华食篓", "🧺", BASKET_GEN, "dough_1", Some("basket_6"),  bsc, Some("item_icon_10105.png")));
    items.push(ItemDef::generator("basket_6",  ChainType::Basket, 6,  "竹华食篓", "🧺", BASKET_GEN, "dough_1", Some("basket_7"),  bsc, Some("item_icon_10106.png")));
    items.push(ItemDef::generator("basket_7",  ChainType::Basket, 7,  "竹华食篓", "🧺", BASKET_GEN, "dough_1", Some("basket_8"),  bsc, Some("item_icon_10107.png")));
    items.push(ItemDef::generator("basket_8",  ChainType::Basket, 8,  "精品食篓", "🧺", BASKET_GEN, "dough_1", Some("basket_9"),  bsc, Some("item_icon_10108.png")));
    items.push(ItemDef::generator("basket_9",  ChainType::Basket, 9,  "精品食篓", "🧺", BASKET_GEN, "dough_1", Some("basket_10"), bsc, Some("item_icon_10109.png")));
    items.push(ItemDef::generator("basket_10", ChainType::Basket, 10, "精品食篓", "🧺", BASKET_GEN, "dough_1", Some("basket_11"), bsc, Some("item_icon_10110.png")));
    items.push(ItemDef::generator("basket_11", ChainType::Basket, 11, "顶级食篓", "🧺", BASKET_GEN, "dough_1", None,             bsc, Some("item_icon_10111.png")));

    // ── 面团 (Dough/Pastry) child chain (15 levels) ───────────────────────────
    let dc = (0.95, 0.85, 0.65); // light tan
    items.push(ItemDef::child("dough_1",  ChainType::Dough, 1,  "面团",     "🫓", Some("dough_2"),  dc, Some("item_icon_20101.png")));
    items.push(ItemDef::child("dough_2",  ChainType::Dough, 2,  "汤圆",     "🍡", Some("dough_3"),  dc, Some("item_icon_20102.png")));
    items.push(ItemDef::child("dough_3",  ChainType::Dough, 3,  "花卷",     "🥐", Some("dough_4"),  dc, Some("item_icon_20103.png")));
    items.push(ItemDef::child("dough_4",  ChainType::Dough, 4,  "桂花糕",   "🎂", Some("dough_5"),  dc, Some("item_icon_20104.png")));
    items.push(ItemDef::child("dough_5",  ChainType::Dough, 5,  "玫瑰饼",   "🌸", Some("dough_6"),  dc, Some("item_icon_20105.png")));
    items.push(ItemDef::child("dough_6",  ChainType::Dough, 6,  "蛋黄酥",   "🥮", Some("dough_7"),  dc, Some("item_icon_20106.png")));
    items.push(ItemDef::child("dough_7",  ChainType::Dough, 7,  "海棠糕",   "🍮", Some("dough_8"),  dc, Some("item_icon_20107.png")));
    items.push(ItemDef::child("dough_8",  ChainType::Dough, 8,  "宫廷糕点", "🍰", Some("dough_9"),  dc, Some("item_icon_20108.png")));
    items.push(ItemDef::child("dough_9",  ChainType::Dough, 9,  "艾草青团", "🟢", Some("dough_10"), dc, Some("item_icon_20109.png")));
    items.push(ItemDef::child("dough_10", ChainType::Dough, 10, "柿柿如意", "🎑", Some("dough_11"), dc, Some("item_icon_20110.png")));
    items.push(ItemDef::child("dough_11", ChainType::Dough, 11, "桃花酥",   "🌺", Some("dough_12"), dc, Some("item_icon_20111.png")));
    items.push(ItemDef::child("dough_12", ChainType::Dough, 12, "凤梨酥",   "🍍", Some("dough_13"), dc, Some("item_icon_20112.png")));
    items.push(ItemDef::child("dough_13", ChainType::Dough, 13, "杏仁酥",   "🌰", Some("dough_14"), dc, Some("item_icon_20113.png")));
    items.push(ItemDef::child("dough_14", ChainType::Dough, 14, "核桃酥",   "🥜", Some("dough_15"), dc, Some("item_icon_20114.png")));
    items.push(ItemDef::child("dough_15", ChainType::Dough, 15, "玉兔摘柿盒", "🐇", None,           dc, Some("item_icon_20115.png")));

    // ── 西瓜 (Watermelon) rare child chain (7 levels) ────────────────────────
    let wc = (0.35, 0.75, 0.35); // green
    items.push(ItemDef::child("watermelon_1", ChainType::Watermelon, 1, "西瓜", "🍉", Some("watermelon_2"), wc, Some("item_icon_20201.png")));
    items.push(ItemDef::child("watermelon_2", ChainType::Watermelon, 2, "西瓜", "🍉", Some("watermelon_3"), wc, Some("item_icon_20202.png")));
    items.push(ItemDef::child("watermelon_3", ChainType::Watermelon, 3, "西瓜", "🍉", Some("watermelon_4"), wc, Some("item_icon_20203.png")));
    items.push(ItemDef::child("watermelon_4", ChainType::Watermelon, 4, "西瓜", "🍉", Some("watermelon_5"), wc, Some("item_icon_20204.png")));
    items.push(ItemDef::child("watermelon_5", ChainType::Watermelon, 5, "西瓜", "🍉", Some("watermelon_6"), wc, Some("item_icon_20205.png")));
    items.push(ItemDef::child("watermelon_6", ChainType::Watermelon, 6, "西瓜", "🍉", Some("watermelon_7"), wc, Some("item_icon_20206.png")));
    items.push(ItemDef::child("watermelon_7", ChainType::Watermelon, 7, "极品西瓜", "🍉", None,             wc, Some("item_icon_20207.png")));

    // ── 手作盒 (CraftBox) generator chain (11 levels) ─────────────────────────
    // Lv1-4: merge only; Lv5-11: weighted-generates 灯笼
    let cbc = (0.65, 0.45, 0.25); // dark brown
    items.push(ItemDef::child("craftBox_1", ChainType::CraftBox, 1, "手作盒", "📦", Some("craftBox_2"), cbc, Some("item_icon_10301.png")));
    items.push(ItemDef::child("craftBox_2", ChainType::CraftBox, 2, "手作盒", "📦", Some("craftBox_3"), cbc, Some("item_icon_10302.png")));
    items.push(ItemDef::child("craftBox_3", ChainType::CraftBox, 3, "手作盒", "📦", Some("craftBox_4"), cbc, Some("item_icon_10303.png")));
    items.push(ItemDef::child("craftBox_4", ChainType::CraftBox, 4, "手作盒", "📦", Some("craftBox_5"), cbc, Some("item_icon_10304.png")));
    items.push(ItemDef::generator("craftBox_5",  ChainType::CraftBox, 5,  "精制手作盒", "📦", CRAFTBOX_GEN, "lantern_1", Some("craftBox_6"),  cbc, Some("item_icon_10305.png")));
    items.push(ItemDef::generator("craftBox_6",  ChainType::CraftBox, 6,  "精制手作盒", "📦", CRAFTBOX_GEN, "lantern_1", Some("craftBox_7"),  cbc, Some("item_icon_10306.png")));
    items.push(ItemDef::generator("craftBox_7",  ChainType::CraftBox, 7,  "精制手作盒", "📦", CRAFTBOX_GEN, "lantern_1", Some("craftBox_8"),  cbc, Some("item_icon_10307.png")));
    items.push(ItemDef::generator("craftBox_8",  ChainType::CraftBox, 8,  "高级手作盒", "📦", CRAFTBOX_GEN, "lantern_1", Some("craftBox_9"),  cbc, Some("item_icon_10308.png")));
    items.push(ItemDef::generator("craftBox_9",  ChainType::CraftBox, 9,  "高级手作盒", "📦", CRAFTBOX_GEN, "lantern_1", Some("craftBox_10"), cbc, Some("item_icon_10309.png")));
    items.push(ItemDef::generator("craftBox_10", ChainType::CraftBox, 10, "高级手作盒", "📦", CRAFTBOX_GEN, "lantern_1", Some("craftBox_11"), cbc, Some("item_icon_10310.png")));
    items.push(ItemDef::generator("craftBox_11", ChainType::CraftBox, 11, "顶级手作盒", "📦", CRAFTBOX_GEN, "lantern_1", None,                cbc, Some("item_icon_10311.png")));

    // ── 灯笼 (Lantern) child chain (12 levels) ────────────────────────────────
    let lc = (0.95, 0.35, 0.25); // red/orange
    items.push(ItemDef::child("lantern_1",  ChainType::Lantern, 1,  "纸糊灯笼", "🕯️", Some("lantern_2"),  lc, Some("item_icon_20501.png")));
    items.push(ItemDef::child("lantern_2",  ChainType::Lantern, 2,  "圆灯笼",   "🏮", Some("lantern_3"),  lc, Some("item_icon_20502.png")));
    items.push(ItemDef::child("lantern_3",  ChainType::Lantern, 3,  "彩灯笼",   "🪔", Some("lantern_4"),  lc, Some("item_icon_20503.png")));
    items.push(ItemDef::child("lantern_4",  ChainType::Lantern, 4,  "宫廷灯",   "💡", Some("lantern_5"),  lc, Some("item_icon_20504.png")));
    items.push(ItemDef::child("lantern_5",  ChainType::Lantern, 5,  "宫廷灯",   "💡", Some("lantern_6"),  lc, Some("item_icon_20505.png")));
    items.push(ItemDef::child("lantern_6",  ChainType::Lantern, 6,  "花灯",     "🎑", Some("lantern_7"),  lc, Some("item_icon_20506.png")));
    items.push(ItemDef::child("lantern_7",  ChainType::Lantern, 7,  "花灯",     "🎑", Some("lantern_8"),  lc, Some("item_icon_20507.png")));
    items.push(ItemDef::child("lantern_8",  ChainType::Lantern, 8,  "精品花灯", "✨", Some("lantern_9"),  lc, Some("item_icon_20508.png")));
    items.push(ItemDef::child("lantern_9",  ChainType::Lantern, 9,  "精品花灯", "✨", Some("lantern_10"), lc, Some("item_icon_20509.png")));
    items.push(ItemDef::child("lantern_10", ChainType::Lantern, 10, "龙凤花灯", "🔆", Some("lantern_11"), lc, Some("item_icon_20510.png")));
    items.push(ItemDef::child("lantern_11", ChainType::Lantern, 11, "龙凤花灯", "🔆", Some("lantern_12"), lc, Some("item_icon_20511.png")));
    items.push(ItemDef::child("lantern_12", ChainType::Lantern, 12, "九龙玉灯", "🌟", None,               lc, Some("item_icon_20512.png")));

    // ── 妆奁 (Dresser) generator chain (11 levels) ────────────────────────────
    // Lv1-4: merge only; Lv5-11: weighted-generates 戒指 + rare 平安扣
    let drc = (0.85, 0.55, 0.75); // pink/purple
    items.push(ItemDef::child("dresser_1", ChainType::Dresser, 1, "妆奁", "💄", Some("dresser_2"), drc, Some("item_icon_10401.png")));
    items.push(ItemDef::child("dresser_2", ChainType::Dresser, 2, "妆奁", "💄", Some("dresser_3"), drc, Some("item_icon_10402.png")));
    items.push(ItemDef::child("dresser_3", ChainType::Dresser, 3, "妆奁", "💄", Some("dresser_4"), drc, Some("item_icon_10403.png")));
    items.push(ItemDef::child("dresser_4", ChainType::Dresser, 4, "妆奁", "💄", Some("dresser_5"), drc, Some("item_icon_10404.png")));
    items.push(ItemDef::generator("dresser_5",  ChainType::Dresser, 5,  "漆雕妆奁", "💄", DRESSER_GEN, "ring_1", Some("dresser_6"),  drc, Some("item_icon_10405.png")));
    items.push(ItemDef::generator("dresser_6",  ChainType::Dresser, 6,  "漆雕妆奁", "💄", DRESSER_GEN, "ring_1", Some("dresser_7"),  drc, Some("item_icon_10406.png")));
    items.push(ItemDef::generator("dresser_7",  ChainType::Dresser, 7,  "漆雕妆奁", "💄", DRESSER_GEN, "ring_1", Some("dresser_8"),  drc, Some("item_icon_10407.png")));
    items.push(ItemDef::generator("dresser_8",  ChainType::Dresser, 8,  "金丝妆奁", "💄", DRESSER_GEN, "ring_1", Some("dresser_9"),  drc, Some("item_icon_10408.png")));
    items.push(ItemDef::generator("dresser_9",  ChainType::Dresser, 9,  "金丝妆奁", "💄", DRESSER_GEN, "ring_1", Some("dresser_10"), drc, Some("item_icon_10409.png")));
    items.push(ItemDef::generator("dresser_10", ChainType::Dresser, 10, "金丝妆奁", "💄", DRESSER_GEN, "ring_1", Some("dresser_11"), drc, Some("item_icon_10410.png")));
    items.push(ItemDef::generator("dresser_11", ChainType::Dresser, 11, "顶级妆奁", "💄", DRESSER_GEN, "ring_1", None,              drc, Some("item_icon_10411.png")));

    // ── 戒指 (Ring/Jewelry) child chain (11 levels) ───────────────────────────
    let rc = (0.85, 0.75, 0.25); // gold
    items.push(ItemDef::child("ring_1",  ChainType::Ring, 1,  "金戒指",   "💍", Some("ring_2"),  rc, Some("item_icon_20601.png")));
    items.push(ItemDef::child("ring_2",  ChainType::Ring, 2,  "雕花耳坠", "📿", Some("ring_3"),  rc, Some("item_icon_20602.png")));
    items.push(ItemDef::child("ring_3",  ChainType::Ring, 3,  "银镯子",   "⭕", Some("ring_4"),  rc, Some("item_icon_20603.png")));
    items.push(ItemDef::child("ring_4",  ChainType::Ring, 4,  "翡翠镯",   "💚", Some("ring_5"),  rc, Some("item_icon_20604.png")));
    items.push(ItemDef::child("ring_5",  ChainType::Ring, 5,  "龙凤佩",   "💎", Some("ring_6"),  rc, Some("item_icon_20605.png")));
    items.push(ItemDef::child("ring_6",  ChainType::Ring, 6,  "金步摇",   "🌟", Some("ring_7"),  rc, Some("item_icon_20606.png")));
    items.push(ItemDef::child("ring_7",  ChainType::Ring, 7,  "云纹玉佩", "🔮", Some("ring_8"),  rc, Some("item_icon_20607.png")));
    items.push(ItemDef::child("ring_8",  ChainType::Ring, 8,  "凤钗",     "🦚", Some("ring_9"),  rc, Some("item_icon_20608.png")));
    items.push(ItemDef::child("ring_9",  ChainType::Ring, 9,  "蝶恋花钗", "🦋", Some("ring_10"), rc, Some("item_icon_20609.png")));
    items.push(ItemDef::child("ring_10", ChainType::Ring, 10, "翠玉观音", "🏺", Some("ring_11"), rc, Some("item_icon_20610.png")));
    items.push(ItemDef::child("ring_11", ChainType::Ring, 11, "九龙玉璧", "☯️", None,            rc, Some("item_icon_20611.png")));

    // ── 平安扣 (PeaceLock) rare child chain (7 levels) ───────────────────────
    let plc = (0.55, 0.75, 0.85); // jade/teal
    items.push(ItemDef::child("peaceLock_1", ChainType::PeaceLock, 1, "平安扣", "🪬", Some("peaceLock_2"), plc, Some("item_icon_20901.png")));
    items.push(ItemDef::child("peaceLock_2", ChainType::PeaceLock, 2, "平安扣", "🪬", Some("peaceLock_3"), plc, Some("item_icon_20902.png")));
    items.push(ItemDef::child("peaceLock_3", ChainType::PeaceLock, 3, "平安扣", "🪬", Some("peaceLock_4"), plc, Some("item_icon_20903.png")));
    items.push(ItemDef::child("peaceLock_4", ChainType::PeaceLock, 4, "平安扣", "🪬", Some("peaceLock_5"), plc, Some("item_icon_20904.png")));
    items.push(ItemDef::child("peaceLock_5", ChainType::PeaceLock, 5, "平安扣", "🪬", Some("peaceLock_6"), plc, Some("item_icon_20905.png")));
    items.push(ItemDef::child("peaceLock_6", ChainType::PeaceLock, 6, "平安扣", "🪬", Some("peaceLock_7"), plc, Some("item_icon_20906.png")));
    items.push(ItemDef::child("peaceLock_7", ChainType::PeaceLock, 7, "极品平安扣", "🪬", None,            plc, Some("item_icon_20907.png")));

    // ── 织布机 (Loom) generator chain (11 levels) ─────────────────────────────
    // Lv1-4: merge only; Lv5-11: weighted-generates 布匹
    let lmc = (0.55, 0.65, 0.85); // blue
    items.push(ItemDef::child("loom_1", ChainType::Loom, 1, "织布机", "🪡", Some("loom_2"), lmc, Some("item_icon_10501.png")));
    items.push(ItemDef::child("loom_2", ChainType::Loom, 2, "织布机", "🪡", Some("loom_3"), lmc, Some("item_icon_10502.png")));
    items.push(ItemDef::child("loom_3", ChainType::Loom, 3, "织布机", "🪡", Some("loom_4"), lmc, Some("item_icon_10503.png")));
    items.push(ItemDef::child("loom_4", ChainType::Loom, 4, "织布机", "🪡", Some("loom_5"), lmc, Some("item_icon_10504.png")));
    items.push(ItemDef::generator("loom_5",  ChainType::Loom, 5,  "精制织布机", "🪡", LOOM_GEN, "fabric_1", Some("loom_6"),  lmc, Some("item_icon_10505.png")));
    items.push(ItemDef::generator("loom_6",  ChainType::Loom, 6,  "精制织布机", "🪡", LOOM_GEN, "fabric_1", Some("loom_7"),  lmc, Some("item_icon_10506.png")));
    items.push(ItemDef::generator("loom_7",  ChainType::Loom, 7,  "精制织布机", "🪡", LOOM_GEN, "fabric_1", Some("loom_8"),  lmc, Some("item_icon_10507.png")));
    items.push(ItemDef::generator("loom_8",  ChainType::Loom, 8,  "高级织布机", "🪡", LOOM_GEN, "fabric_1", Some("loom_9"),  lmc, Some("item_icon_10508.png")));
    items.push(ItemDef::generator("loom_9",  ChainType::Loom, 9,  "高级织布机", "🪡", LOOM_GEN, "fabric_1", Some("loom_10"), lmc, Some("item_icon_10509.png")));
    items.push(ItemDef::generator("loom_10", ChainType::Loom, 10, "高级织布机", "🪡", LOOM_GEN, "fabric_1", Some("loom_11"), lmc, Some("item_icon_10510.png")));
    items.push(ItemDef::generator("loom_11", ChainType::Loom, 11, "顶级织布机", "🪡", LOOM_GEN, "fabric_1", None,            lmc, Some("item_icon_10511.png")));

    // ── 布匹 (Fabric) child chain (5 levels) ──────────────────────────────────
    // Lv5: max level AND a click-generator for 荷包
    let fc = (0.75, 0.85, 0.95); // light blue
    items.push(ItemDef::child("fabric_1", ChainType::Fabric, 1, "白色布匹", "🧵", Some("fabric_2"), fc, Some("item_icon_30101.png")));
    items.push(ItemDef::child("fabric_2", ChainType::Fabric, 2, "彩色布匹", "🎨", Some("fabric_3"), fc, Some("item_icon_30102.png")));
    items.push(ItemDef::child("fabric_3", ChainType::Fabric, 3, "描金布匹", "✨", Some("fabric_4"), fc, Some("item_icon_30103.png")));
    items.push(ItemDef::child("fabric_4", ChainType::Fabric, 4, "绣花布匹", "🌺", Some("fabric_5"), fc, Some("item_icon_30104.png")));
    // fabric_5 is max level AND a click-generator that produces 荷包 (no merge available)
    items.push(ItemDef::generator("fabric_5", ChainType::Fabric, 5, "绫罗布匹", "🎀", FABRIC5_GEN, "pouch_1", None, fc, Some("item_icon_30105.png")));

    // ── 荷包 (Pouch) child chain (10 levels) ──────────────────────────────────
    let poc = (0.65, 0.75, 0.95); // periwinkle
    items.push(ItemDef::child("pouch_1",  ChainType::Pouch, 1,  "绣花荷包",     "👛", Some("pouch_2"),  poc, Some("item_icon_20701.png")));
    items.push(ItemDef::child("pouch_2",  ChainType::Pouch, 2,  "绣花荷包",     "👛", Some("pouch_3"),  poc, Some("item_icon_20702.png")));
    items.push(ItemDef::child("pouch_3",  ChainType::Pouch, 3,  "锦绣荷包",     "👜", Some("pouch_4"),  poc, Some("item_icon_20703.png")));
    items.push(ItemDef::child("pouch_4",  ChainType::Pouch, 4,  "锦绣荷包",     "👜", Some("pouch_5"),  poc, Some("item_icon_20704.png")));
    items.push(ItemDef::child("pouch_5",  ChainType::Pouch, 5,  "香囊荷包",     "🎒", Some("pouch_6"),  poc, Some("item_icon_20705.png")));
    items.push(ItemDef::child("pouch_6",  ChainType::Pouch, 6,  "香囊荷包",     "🎒", Some("pouch_7"),  poc, Some("item_icon_20706.png")));
    items.push(ItemDef::child("pouch_7",  ChainType::Pouch, 7,  "云锦荷包",     "💼", Some("pouch_8"),  poc, Some("item_icon_20707.png")));
    items.push(ItemDef::child("pouch_8",  ChainType::Pouch, 8,  "云锦荷包",     "💼", Some("pouch_9"),  poc, Some("item_icon_20708.png")));
    items.push(ItemDef::child("pouch_9",  ChainType::Pouch, 9,  "御赐荷包",     "🏮", Some("pouch_10"), poc, Some("item_icon_20709.png")));
    items.push(ItemDef::child("pouch_10", ChainType::Pouch, 10, "极品御赐荷包", "🌟", None,             poc, Some("item_icon_20710.png")));

    // ── 红色漆盒 (RedBox) reward gift box (2 levels) ─────────────────────────
    // Lv1 opens into teapot_1/basket_1/loom_1; Lv2 opens into teapot_2/basket_2/loom_2.
    let rdc = (0.90, 0.20, 0.15); // deep red
    items.push(ItemDef::generator("redBox_1", ChainType::RedBox, 1, "红色漆盒", "🧧", RED_BOX_LV1_GEN, "teapot_1", Some("redBox_2"), rdc, Some("item_icon_30201.png")));
    items.push(ItemDef::generator("redBox_2", ChainType::RedBox, 2, "红色漆盒", "🧧", RED_BOX_LV2_GEN, "teapot_2", None,             rdc, Some("item_icon_30202.png")));

    // ── 绿色漆盒 (GreenBox) reward gift box (2 levels) ───────────────────────
    // Lv1 opens into poultry_1/dresser_1/craftBox_1; Lv2 opens into _2 variants.
    let gbc = (0.20, 0.65, 0.30); // deep green
    items.push(ItemDef::generator("greenBox_1", ChainType::GreenBox, 1, "绿色漆盒", "🎁", GREEN_BOX_LV1_GEN, "poultry_1", Some("greenBox_2"), gbc, Some("item_icon_30301.png")));
    items.push(ItemDef::generator("greenBox_2", ChainType::GreenBox, 2, "绿色漆盒", "🎁", GREEN_BOX_LV2_GEN, "poultry_2", None,               gbc, Some("item_icon_30302.png")));

    items
}

/// Lookup table for items by ID.
#[derive(Debug, Resource)]
pub struct ItemDatabase {
    pub items: HashMap<String, ItemDef>,
}

impl ItemDatabase {
    pub fn new() -> Self {
        let mut items = HashMap::new();
        for item in all_items() {
            items.insert(item.id.to_string(), item);
        }
        Self { items }
    }

    pub fn get(&self, id: &str) -> Option<&ItemDef> {
        self.items.get(id)
    }

    /// Check whether two items can be merged.
    ///
    /// Merge is possible when both items:
    /// - exist in the database
    /// - have the same item ID (which implies same chain and same level)
    /// - have a `merge_result_id` (i.e. are not at the maximum level)
    ///
    /// The `chain` field on each `ItemDef` uniquely identifies which production
    /// family the item belongs to; because we require `id_a == id_b`, the chains
    /// are guaranteed to match without a redundant comparison.
    pub fn can_merge(&self, id_a: &str, id_b: &str) -> bool {
        if id_a != id_b {
            return false;
        }
        if let Some(item) = self.get(id_a) {
            // Sanity-check: same id implies same chain and same level
            debug_assert!(
                matches!(self.get(id_b), Some(b) if std::mem::discriminant(&b.chain)
                    == std::mem::discriminant(&item.chain) && b.level == item.level),
                "Two items with the same id must belong to the same chain and level"
            );
            item.merge_result_id.is_some()
        } else {
            false
        }
    }
}

impl Default for ItemDatabase {
    fn default() -> Self {
        Self::new()
    }
}
